```toml
[
build
]
  functions = "functions"
  publish = "public"

[
functions
]
  node_bundler = "esbuild"

[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200

[
dev
]
  functionsPort = 8888
```
